#!/bin/sh

#cleanup

rm -rf obj_dir
rm -f counter.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace CPU.sv --exe CPU_tb.cpp

#build c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VCPU.mk VCPU

# run executable simulation file
obj_dir/VCPU

