#!/bin/sh

#cleanup

rm -rf obj_dir
rm -f cpu.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
#verilator -Wall --cc --trace CPU.sv --exe CPU_tb.cpp
verilator -Wall --cc --trace CPU.sv --exe f1_tb2.cpp
#verilator -Wall --cc --trace CPU.sv --exe instrmem_tb.cpp

#build c++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VCPU.mk VCPU

# run executable simulation file
obj_dir/VCPU

